f = open("HumptyDumty.txt","r",encoding='utf-8')
a = f.readline()
print("Nội dung dòng đầu:",(a))
b = f.readline()
print("Nội dung dòng thứ 2:",(b))
c = f.readline()
print("Nội dung dòng thứ 3:",(c))
d = f.readline()
print("Nội dung dòng thứ 4:",(d))
####
t = open("HumptyDumty.txt","r")
content = t.read()
print(content)
t.close()
